Use nca as a library
np-guard/baseline-rules-verifier pull request #24
Opened 2022-06-13 08:25 UTC by shireenf-ibm

#22 ..
Hi @zivnevo ,
Some notes on this commit:

Runnig NCA's main function (instead of as a subprocess) caused some issues:
1. stdout and stderr print:
calling the main function , automatically prints its output, so in order to skip this , I did the following:
-> redirected the sys.stdout into a buffer before calling nca  (then after it finishes return it to sys.stdout)
-> unfortunately, redirecting sys.stderr into a buffer didn't work, so I used a hack to "hide" it when the debug mode is off with a `@contextmanager` method

2. removing the "tmp/<rule> (the NetworkPolicy) file caused an exception :

> PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: '..\\tmp\\allow-access-to-google.yaml'
 
in this commit , I wrapped the remove call with a try..except block. 
      ```
      try:
                os.remove(rule_filename)
            except PermissionError:
                print(f'{rule_filename} could not be deleted automatically', file=sys.stderr)
```
Another solution may be to check and wait until the "nca.exe" is finished and try to remove the file then.
Or may it help if we close the networkPolicy files on nca?
would like to know your idea on this

2022-06-13 09:07 UTC, shireenf-ibm commented
> #22 .. Hi @zivnevo , Some notes on this commit:
> 
> Runnig NCA's main function (instead of as a subprocess) caused some issues:
> 
>     1. stdout and stderr print:
>        calling the main function , automatically prints its output, so in order to skip this , I did the following:
>        -> redirected the sys.stdout into a buffer before calling nca  (then after it finishes return it to sys.stdout)
>        -> unfortunately, redirecting sys.stderr into a buffer didn't work, so I used a hack to "hide" it when the debug mode is off with a `@contextmanager` method
> 
>     2. removing the "tmp/ (the NetworkPolicy) file caused an exception :
> 
> 
> > PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: '..\tmp\allow-access-to-google.yaml'
> 
> in this commit , I wrapped the remove call with a try..except block. `try: os.remove(rule_filename) except PermissionError: print(f'{rule_filename} could not be deleted automatically', file=sys.stderr)` Another solution may be to check and wait until the "nca.exe" is finished and try to remove the file then. Or may it help if we close the networkPolicy files on nca? would like to know your idea on this

While hiding the nca's stderr works in my local ws, seems that it doesn't work here
I see that "warnings" from nca are printed to  "run all tests" log

2022-06-13 10:30 UTC, zivnevo commented
> #22 .. Hi @zivnevo , Some notes on this commit:
> 
> Runnig NCA's main function (instead of as a subprocess) caused some issues:
> 
>     1. stdout and stderr print:
>        calling the main function , automatically prints its output, so in order to skip this , I did the following:
>        -> redirected the sys.stdout into a buffer before calling nca  (then after it finishes return it to sys.stdout)
>        -> unfortunately, redirecting sys.stderr into a buffer didn't work, so I used a hack to "hide" it when the debug mode is off with a `@contextmanager` method
> 
>     2. removing the "tmp/ (the NetworkPolicy) file caused an exception on my local workspace :
> 
> 
> > PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: '..\tmp\allow-access-to-google.yaml'
> 
> in this commit , I wrapped the remove call with a try..except block. `try: os.remove(rule_filename) except PermissionError: print(f'{rule_filename} could not be deleted automatically', file=sys.stderr)` Another solution may be to check and wait until the "nca.exe" is finished and try to remove the file then. Or may it help if we close the networkPolicy files on nca? would like to know your idea on this

I think NCA should close the file when it's done. I hope it will help. Otherwise we are going to leave many leftover files.

2022-06-13 10:59 UTC, zivnevo requested changes
Great! Please see comments

2022-06-13 10:59 UTC, zivnevo commented on requirements.txt
>  Flask>=2.0.0
```suggestion
```
Remove all requirements that come from `network-config-analyzer`. Leave just `PyYaml` and `network-config-analyzer`, which `baseline-rules-verifier` uses directly.

2022-06-13 10:59 UTC, zivnevo commented on Dockerfile
> +RUN pip install --no-deps -r ./requirements.txt
Why `--no-deps`?

2022-06-13 10:59 UTC, zivnevo commented on .github/workflows/test-push.yml
> +          pip install network-config-analyzer
```suggestion
          pip install -r network-config-analyzer/requirements.txt
```
We still want to use `requirements.txt` in case `baseline-rules-verifier` will have dependencies of its own.

2022-06-13 12:00 UTC, shireenf-ibm commented on Dockerfile
> +RUN pip install --no-deps -r ./requirements.txt
when I  run it without `--no-deps` , I get some  `conflicting dependencies errors.`
I assume that this happen because the `ghcr.io/np-guard/nca:1.0` already includes the nca's requirements.

2022-06-13 12:11 UTC, shireenf-ibm commented on Dockerfile
> +RUN pip install --no-deps -r ./requirements.txt
I tried to run without it (with the updated requirements), and added `RUN python -m pip install --upgrade pip` above these commands, I am getting this:

![image](https://user-images.githubusercontent.com/82180114/173350742-641b8060-e2f5-4be6-849c-e2a6ae666901.png)

2022-06-13 12:15 UTC, shireenf-ibm commented on Dockerfile
> +RUN pip install --no-deps -r ./requirements.txt
However, if I run with `--no-deps` , the Dockerfile is been deployed successfully, but its Log fails with (only after updating the requirements.txt file) :

![image](https://user-images.githubusercontent.com/82180114/173351147-c5bd7c6f-c3ea-419d-9bfc-42700687549c.png)

2022-06-13 12:37 UTC, shireenf-ibm commented
warnings are still being printed to the log, so redirecting stderr to the buffer didn't work too.
I may keep the code as is now or redirect only the stdout.( and "not touch" the stderr)?

2022-06-15 12:31 UTC, zivnevo requested changes
Just the version change (so file closing works properly)

2022-06-15 12:31 UTC, zivnevo commented on requirements.txt
> +network-config-analyzer>=1.3.1
```suggestion
network-config-analyzer>=1.4.1
```

2022-06-15 12:34 UTC, zivnevo approved these changes

2022-06-15 12:34 UTC, zivnevo commented on requirements.txt
> +network-config-analyzer>=1.3.1
```suggestion
network-config-analyzer>=1.4.1
```

2022-06-15 12:38 UTC, merged